### ISSUE TITLE
is there a way to transfer the old data into the updated version of the counter?

### ISSUE THREAD

**Issue by Mattxew** [avi12/youtube-time-manager-feedback#1]
title, thanks. :)

**Comment by Mattxew** [comment]
^ ive downloaded the old data, don't know if there's a way to transfer this json file into the updated version.

**Comment by avi12** [comment]
Sadly there isn't
The old data is simply about numbers, whereas the new data format involves tracking videos by dates, video IDs, timestamps, etc.
If there was a way to transfer the old data to be a part of the new one, rest assured that I would've already taken care of it
