### ISSUE TITLE
[Bug]  - YT Icon - Refresh

### ISSUE THREAD

**Issue by Lucasark** [avi12/youtube-time-manager-feedback#11]
### Describe the bug

Still with problem with YT Icon, I do not think the refresh icon worked so well

<img width="461" alt="image" src="https://github.com/avi12/youtube-time-manager-feedback/assets/31750882/4f1d2aa5-f21b-4555-aef0-3555bb166ecb">

<img width="447" alt="image" src="https://github.com/avi12/youtube-time-manager-feedback/assets/31750882/412cd66c-92c8-42aa-80f7-58695c432be0">

In year still with wrong image, in day is with correct one. 

#5 

### How to reproduce

Play music

### Expected behavior

Set right icon

### What browser(s) can you reproduce the issue on?

Chrome

### What OS does it occur on?

Windows

### What's the extension version you're running?

3.0.10

### Make sure the bug wasn't reported before

- [X] I'm the first one to [report](https://github.com/avi12/youtube-time-manager-feedback/issues?q=is%3Aissue) it

### Make sure that YouTube Time Manager is the only extension running on YouTube

- [X] The issue still persists after disabling any other YouTube extension

**Comment by avi12** [comment]
Please reopen the [issue](https://github.com/avi12/youtube-time-manager-feedback/issues/5) instead of creating this one
