### ISSUE TITLE
[Bug]  youtube-time-manager-feedback - Weekly chart and Configuration Bar

### ISSUE THREAD

**Issue by Lucasark** [avi12/youtube-time-manager-feedback#2]
### Describe the bug

<img width="451" alt="image" src="https://github.com/avi12/youtube-time-manager-feedback/assets/31750882/f6d18c78-b7b7-4ff3-8de4-1ab1050755db">

<img width="403" alt="image" src="https://github.com/avi12/youtube-time-manager-feedback/assets/31750882/febd827b-bfe8-451b-8ba0-85f810311a1e">

### How to reproduce

Just clicked the icon

### Expected behavior

Show Data

And, I think that need show something else on configuration

### What browser(s) can you reproduce the issue on?

Chrome

### What OS does it occur on?

Windows

### What's the extension version you're running?

3.0.1

### Make sure the bug wasn't reported before

- [X] I'm the first one to [report](https://github.com/avi12/youtube-auto-hd/issues?q=is%3Aissue) it

### Make sure that YouTube Time Manager is the only extension running on YouTube

- [X] The issue still persists after disabling any other YouTube extension

**Comment by avi12** [comment]
Huh, that looks like a theming issue
For some reason, I forgot to implement the dark theme, thanks for the heads up!
It will be fixed in 3.0.3+

**Comment by avi12** [comment]
Regarding the weekly chart, once you get the update, can you export the data? I'm not sure why the date is invalid

**Comment by Lucasark** [comment]
I can only export "old data", to "new data" it show block click:
<img width="418" alt="image" src="https://github.com/avi12/youtube-time-manager-feedback/assets/31750882/5a8f081c-7f13-4d92-a8b2-0312b5b5b21c">

[(OLD) YouTube Time Manager OlD Data.json](https://github.com/avi12/youtube-time-manager-feedback/files/13963319/YouTube.Time.Manager.OlD.Data.json)

**Comment by avi12** [comment]
Update 3.0.3+ lets  you click the "Export new data" button
I forgot to implement the mechanism that enables that button, as I concentrated my main efforts on the pop-up within YouTube.com

**Comment by Lucasark** [comment]
> Update 3.0.3+ lets you click the "Export new data" button I forgot to implement the mechanism that enables that button, as I concentrated my main efforts on the pop-up within YouTube.com

I am waiting the 3.0.3 go to Chrome - Mac, i am trying to update but the version is still on 3.0.1

<img width="701" alt="image" src="https://github.com/avi12/youtube-time-manager-feedback/assets/31750882/fd32c9aa-c649-4c45-a98d-eee553f58c43">

**Comment by avi12** [comment]
![image](https://github.com/avi12/youtube-time-manager-feedback/assets/6422804/4b422538-f608-4f57-bb83-d985759ed785)

**Comment by Lucasark** [comment]
> ![image](https://private-user-images.githubusercontent.com/6422804/297387565-4b422538-f608-4f57-bb83-d985759ed785.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0OTcxNDIsIm5iZiI6MTcwNTQ5Njg0MiwicGF0aCI6Ii82NDIyODA0LzI5NzM4NzU2NS00YjQyMjUzOC1mNjA4LTRmNTctYmI4My1kOTg1NzU5ZWQ3ODUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTdUMTMwNzIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjYzMWM0NWFkMGFiODEyYWYwNDA0NGI1ODNhMzJlMzM1NTJiNWM4ODk4NzE1ZjhkNDM1ZDdiOWIyNzBjYzdiMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.tG_7xiQ-mhBscHfP9w8E1BegLUGQulYhm7HGcAErrdQ)

https://chromewebstore.google.com/detail/youtube-time-manager/fpoooibdndpjcnoodfionoeakeojdjaj

On chromewebstore is still 3.0.1, I wil awaiting few seconds

**Comment by avi12** [comment]
Update 3.0.3 is now live on CWS

**Comment by Lucasark** [comment]
[YouTube Time Manager Data.json](https://github.com/avi12/youtube-time-manager-feedback/files/13976460/YouTube.Time.Manager.Data.json)
New data,

- About configuration is good now, i can see haha.
- About Weekly chart still bugged

**Comment by avi12** [comment]
Huh, apparently date like the following is invalid:
```
09:00:00 GMT-0300 (Horário Padrão de Brasília)
```

**Comment by avi12** [comment]
@Lucasark Please open the Chrome Devtools (<kbd>F12</kbd>), in the Console tab type:
```ts
new Date();
```
and take a screenshot

**Comment by Lucasark** [comment]
> @Lucasark Please open the Chrome Devtools (F12), in the Console tab type:
> 
> ```ts
> new Date();
> ```
> 
> and take a screenshot

<img width="1168" alt="image" src="https://github.com/avi12/youtube-time-manager-feedback/assets/31750882/885fe810-e98f-46cd-8fdb-5363670fc05f">

**Comment by avi12** [comment]
That's so strange
For some reason, the extension saved a timestamp without the date, even though `new Date()` does return a date

**Comment by avi12** [comment]
Ok, I figured out the issue
When I do:
```ts
new Date().toLocaleDateString();
```
I get `1/20/2024`, which can be inserted directly into `new Date()`
However, in Brazilian Portuguese Chrome, the command above yields `20/01/2024`, which cannot be inserted into `new Date()`

**Comment by Lucasark** [comment]
> Ok, I figured out the issue When I do:
> 
> ```ts
> new Date().toLocaleDateString();
> ```
> 
> I get `1/20/2024`, which can be inserted directly into `new Date()` However, in Brazilian Portuguese Chrome, the command above yields `20/01/2024`, which cannot be inserted into `new Date()`

<img width="458" alt="image" src="https://github.com/avi12/youtube-time-manager-feedback/assets/31750882/ae571540-a973-4995-880e-dc0a57ef8eb0">
You can use options

**Comment by avi12** [comment]
That's very interesting. I'll probably use it indeed

**Comment by avi12** [comment]
@Lucasark Please try to sideload: [youtube-time-manager-3.0.7.zip](https://github.com/avi12/youtube-time-manager-feedback/files/13999420/youtube-time-manager-3.0.7.zip)

**Comment by avi12** [comment]
I pushed this version
If the issue repeats, feel free to reopen it
