### ISSUE TITLE
[Bug] After changing playback speed of a video, timer continues even though no video is being played

### ISSUE THREAD

**Issue by it0na72** [avi12/youtube-time-manager-feedback#21]
### Describe the bug

https://github.com/avi12/youtube-time-manager-feedback/assets/56265972/b1db312d-3ef6-46cb-b54c-50b39418aacd

### How to reproduce

Increase video speed and then decrease it.

### Expected behavior

Should time depending on the speed of the video and decrease speed accordingly

### What browser(s) can you reproduce the issue on?

Chrome

### What OS does it occur on?

Windows

### What's the extension version you're running?

3.1.2

### Make sure the bug wasn't reported before

- [X] I'm the first one to [report](/avi12/youtube-time-manager-feedback/issues?q=is%3Aissue+) it

### Make sure that YouTube Time Manager is the only extension running on YouTube

- [X] The issue still persists after disabling any other YouTube extension

**Comment by avi12** [comment]
As a hotfix, pausing the video should work, as well as reloading every video to ensure that the timer stops running
Side note, I fundamentally changed the way the extension counts the second such that it listens to [`pause`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/pause_event) and [`play`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/play_event) events

**Comment by avi12** [comment]
Let me know if the issue gets fixed in [youtube-time-manager-3.1.3.zip](https://github.com/avi12/youtube-time-manager-feedback/files/14412494/youtube-time-manager-3.1.3.zip)

**Comment by it0na72** [comment]
Looks fixed, thanks for the quick fix

**Comment by avi12** [comment]
I haven't released it yet

**Comment by avi12** [comment]
@it0na72 I released the update as 3.1.4
