### ISSUE TITLE
[Feature request] Import data  (Eg. when changing browser)

### ISSUE THREAD

**Issue by nabojens** [avi12/youtube-time-manager-feedback#22]
### Is your feature request related to a problem? Please describe

Not really

### Is it a change to the extension's functionality or to the pop-up settings page?

Extension's functionality

### If the latter, please propose a new design on Figma or describe it as detailed as possible

_First of all, i love the new energy you're putting into this, i've been using it since 2022 (According to my old data, which is can't importa. R.I.P data. haha)._ 

**Anyways, it would be awesome with an import data function.** 

I thought there would be one, since you've already made an export function? 

In my case i recenty changed from Chrome to Opera GX (which uses chrome extentions)
Now i have to start over again, again 🥲

**Comment by avi12** [comment]
Working on it #10

**Comment by avi12** [comment]
You can see your old data by querying it, for example from the browser popup page console (I don't remember the exact storage keys)
```ts
chrome.storage.local.get().then(console.log);
chrome.storage.sync.get().then(console.log);
```
