### ISSUE TITLE
[Bug] Can't scroll

### ISSUE THREAD

**Issue by clmnin** [avi12/youtube-time-manager-feedback#4]
### Describe the bug

I can't scroll the popup modal

### How to reproduce

https://github.com/avi12/youtube-time-manager-feedback/assets/17064666/aee73dd1-e1c7-4ba4-a3bf-a6a52d7a3d8d

### Expected behavior

I should be able to scroll

### What browser(s) can you reproduce the issue on?

Chrome

### What OS does it occur on?

macOS

### What's the extension version you're running?

3.0.3

### Make sure the bug wasn't reported before

- [X] I'm the first one to [report](https://github.com/avi12/youtube-auto-hd/issues?q=is%3Aissue) it

### Make sure that YouTube Time Manager is the only extension running on YouTube

- [X] The issue still persists after disabling any other YouTube extension

**Comment by avi12** [comment]
I'll see what I can do about it

**Comment by avi12** [comment]
Please try to sideload: [youtube-time-manager-3.0.6.zip](https://github.com/avi12/youtube-time-manager-feedback/files/13976186/youtube-time-manager-3.0.6.zip)

**Comment by avi12** [comment]
@clmnin

**Comment by clmnin** [comment]
@avi12 Yup, it works now. Thank you
