### ISSUE TITLE
Flashing Icon/Refresh Page + Export/import Data

### ISSUE THREAD

**Issue by SilentMajorityUS** [avi12/youtube-time-manager-feedback#8]
ok, so I am using this on Opera GX Browser and I initially installed the extension from the Opera Addon site.

After I discovered the constant flashing Icon and it telling me to reload issue, I went to search for comments about it which led me to the Chrome store page where you addressed the issue stating it should be fixed in v3.0.7. This led me to discover that the one on the Opera site is still 3.0.0 so I removed that one and installed 3.0.7 from the Chrome store. For me it is still acting the same way with the constant flashing and telling me to reload even on this newest version.

The actual icon flashing and the message doesn't really concern me as long as its doing its job. I just wanted to let you know that it was still doing the same thing, for me anyway, on 3.0.7 from the Chrome store on Opera GX.

Also, before I removed the one from Opera I hit the export data button and got the json file assuming I would be able to plug it into a freshly installed extension and retain my accumulated stats but I don't see a way to do that. Is it possible?

**Comment by avi12** [comment]
As for the flashing icon, apparently it needs to go through another iteration to get it right

**Comment by avi12** [comment]
Please sideload this version and when the icon is flashing, open up the console (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>J</kbd>) and take a screenshot: [youtube-time-manager-3.0.8.zip](https://github.com/avi12/youtube-time-manager-feedback/files/14016014/youtube-time-manager-3.0.8.zip)

**Comment by avi12** [comment]
@SilentMajorityUS Please sideload this version and when the icon is flashing, open up the console (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>J</kbd>) and take a screenshot: [youtube-time-manager-3.0.8.zip](https://github.com/avi12/youtube-time-manager-feedback/files/14016014/youtube-time-manager-3.0.8.zip)

**Comment by avi12** [comment]
I tested it multiple times on my machine and it should work fine
If it doesn't, feel free to reopen the issue
