### ISSUE TITLE
[Bug]  "Extension was updated, reload .." multiple times a day

### ISSUE THREAD

**Issue by Nick2bad4u** [avi12/youtube-time-manager-feedback#9]
### Describe the bug

Randomly the icon starts blinking tell me to reload

### How to reproduce

any video

### Expected behavior

not blinking

### What browser(s) can you reproduce the issue on?

Chromium Edge

### What OS does it occur on?

Windows

### What's the extension version you're running?

3.0.7

### Make sure the bug wasn't reported before

- [X] I'm the first one to [report](https://github.com/avi12/youtube-auto-hd/issues?q=is%3Aissue) it

### Make sure that YouTube Time Manager is the only extension running on YouTube

- [X] The issue still persists after disabling any other YouTube extension

### Additional context

Im on edge and the edge extension was removed, im using the chrome extension, and not sure if this is related. will edge store extension come back?

**Comment by avi12** [comment]
It'll be fixed in 3.0.8
